In [2]:
import numpy as np

In [10]:
states = ["N", "M1", "M2", "M3", "M4", "I1", "I2", "I3", "J", "C", "T"]

# Model A

In [12]:
a_n = [0.6,
       0.4*0.6, 
       0.4*(0.1+0.1*0.8), 
       0.4*(0.1+0.1*0.2*0.5), 
       0.4*(0.1+0.1*0.2*0.5*0.8), 
       0, 
       0, 
       0,
       0.4*0.1*0.2*0.5*0.2*0.2, 
       0.4*0.1*0.2*0.5*0.2*0.7, 
       0.4*0.1*0.2*0.5*0.2*0.1]
list(zip(a_n, states))

[(0.6, 'N'),
 (0.24, 'M1'),
 (0.07200000000000001, 'M2'),
 (0.04400000000000001, 'M3'),
 (0.04320000000000001, 'M4'),
 (0, 'I1'),
 (0, 'I2'),
 (0, 'I3'),
 (0.00016000000000000007, 'J'),
 (0.0005600000000000002, 'C'),
 (8.000000000000003e-05, 'T')]

In [13]:
a_m1 = [0,
        0,
        0.97,
        0.01*0.5,
        0.01*0.5*0.8,
        0.01,
        0,
        0,
        (0.01*0.5*0.2+0.01)*0.2,
        (0.01*0.5*0.2+0.01)*0.7,
        (0.01*0.5*0.2+0.01)*0.1]
list(zip(a_m1, states))

[(0, 'N'),
 (0, 'M1'),
 (0.97, 'M2'),
 (0.005, 'M3'),
 (0.004, 'M4'),
 (0.01, 'I1'),
 (0, 'I2'),
 (0, 'I3'),
 (0.0022, 'J'),
 (0.007699999999999999, 'C'),
 (0.0011, 'T')]

In [15]:
a_m2 = [0,
        0, 
        0, 
        0.5,
        0.4 * 0.8,
        0, 
        0.05,
        0, 
        (0.4*0.2+0.05)*0.2, 
        (0.4*0.2+0.05)*0.7, 
        (0.4*0.2+0.05)*0.1]
list(zip(a_m2, states))

[(0, 'N'),
 (0, 'M1'),
 (0, 'M2'),
 (0.5, 'M3'),
 (0.32000000000000006, 'M4'),
 (0, 'I1'),
 (0.05, 'I2'),
 (0, 'I3'),
 (0.026000000000000002, 'J'),
 (0.091, 'C'),
 (0.013000000000000001, 'T')]

In [17]:
a_m3 = [0,
        0, 
        0, 
        0,
        0.6,
        0, 
        0,
        0.3, 
        0.1*0.2, 
        0.1*0.7, 
        0.1*0.1]
list(zip(a_m3, states))

[(0, 'N'),
 (0, 'M1'),
 (0, 'M2'),
 (0, 'M3'),
 (0.6, 'M4'),
 (0, 'I1'),
 (0, 'I2'),
 (0.3, 'I3'),
 (0.020000000000000004, 'J'),
 (0.06999999999999999, 'C'),
 (0.010000000000000002, 'T')]

In [21]:
a_J = [0, 
       0.1*0.6,
       0.1*(0.1+0.1*0.8),
       0.1*(0.1+0.1*0.2*0.5),
       0.1*(0.1+0.1*0.2*0.5*0.8), 
       0,
       0,
       0,
       0.9+0.1*0.1*0.2*0.5*0.2*0.2,
       0.1*0.1*0.2*0.5*0.2*0.7,
       0.1*0.1*0.2*0.5*0.2*0.1]
list(zip(a_J, states))

[(0, 'N'),
 (0.06, 'M1'),
 (0.018000000000000002, 'M2'),
 (0.011000000000000003, 'M3'),
 (0.010800000000000002, 'M4'),
 (0, 'I1'),
 (0, 'I2'),
 (0, 'I3'),
 (0.9000400000000001, 'J'),
 (0.00014000000000000004, 'C'),
 (2.000000000000001e-05, 'T')]

In [50]:
#alpha(m2, 1)
0.1 * 0.09

0.009

In [51]:
#alpha(m3, 1)
0.7 * 0.055

0.0385

In [52]:
#alpha(m4, 1)
0.9 * 0.054

0.0486

In [75]:
#alpha(N, 2)
0.5 * 0.503474 * 0.6

0.1510422

In [77]:
#alpha(m1, 2)
0.5 * (a_n[1] * 0.503474 + a_J[1] * 0.000201)

0.06042290999999999

In [78]:
#alpha(m2, 2)
0.9 * (a_n[2] * 0.503474 + a_J[2] * 0.000201 + 0.97 * 0.302084)

0.2963477034

In [79]:
#alpha(m3, 2)
0.3 * (a_n[3] * 0.503474 + a_J[3] * 0.000201 + 0.5 * 0.018125 + a_m1[3] * 0.302084)

0.0098183961

In [80]:
#alpha(m4, 2)
0.1 * (a_n[4] * 0.503474 + a_J[4] * 0.000201 + 0.6 * 0.077535 + a_m1[4] * 0.302084 + a_m2[4] * 0.018125)

0.007528158360000001

In [81]:
#alpha(i1, 2)
0.5 * (0.01*0.302084)

0.0015104200000000002

In [82]:
#alpha(i2, 2)
0.5 * (0.05*0.018125)

0.00045312499999999997

In [83]:
#alpha(i2, 2)
0.5 * (0.3*0.077535)

0.01163025

In [84]:
#alpha(J, 2)
0.5 * (a_m1[8]*0.302084 
       + a_m2[8]*0.018125 
       + a_m3[8]*0.077535 
       + 0.2*0.097875 
       + a_n[8]*0.503474 
       + a_J[8]*0.000201)

0.011261499340000002

In [85]:
#alpha(C, 2)
0.5 * (a_m1[9]*0.302084 
       + a_m2[9]*0.018125 
       + a_m3[9]*0.077535 
       + 0.7*0.097875 
       + a_n[9]*0.503474 
       + 0.5*0.000705)

0.03927490862000001

In [87]:
#alpha(N, 3)
0.5 * 0.2563124 * 0.6

0.07689372

In [88]:
#alpha(m1, 3)
0.5 * (a_n[1] * 0.2563124 + a_J[1] * 0.0191103)

0.031330797

In [106]:
#alpha(m2, 3)
0.1 * (a_n[2] * 0.2563124 + a_J[2] * 0.0191103 + 0.97 * 0.1025352 + 0.5*0.0025631)

0.01195391722

In [97]:
#alpha(m3, 3)
0.7 * (a_n[3] * 0.2563124 + a_J[3] * 0.0191103 + 0.5 * 0.5028898 + a_m1[3] * 0.1025352 + 0.5*0.0007689)

0.18468098942999997

In [100]:
#alpha(m4, 3)
0.9 * (a_n[4] * 0.2563124 + a_J[4] * 0.0191103 + 0.6 * 0.0166614 + a_m1[4] * 0.1025352 + a_m2[4] * 0.5028898 + 0.5*0.0197361)

0.17323096834800003

In [107]:
#alpha(i1, 3)
0.5 * (0.01*0.1025352 + 0.5*0.0025631)

0.001153451

In [104]:
#alpha(i2, 3)
0.5 * (0.05*0.5028898 + 0.5*0.0007689)

0.012764470000000003

In [105]:
#alpha(i3, 3)
0.5 * (0.3*0.0166614 + 0.5*0.0197361)

0.007433235

In [108]:
#alpha(J, 3)
0.5 * (a_m1[8]*0.1025352 
       + a_m2[8]*0.5028898 
       + a_m3[8]*0.0166614 
       + 0.2*0.012775 
       + a_n[8]*0.2563124 
       + a_J[8]*0.0191103)

0.016714992318000003

In [114]:
#alpha(C, 3)
0.5 * (a_m1[9]*0.1025352 
       + a_m2[9]*0.5028898 
       + a_m3[9]*0.0166614 
       + 0.7*0.012775 
       + a_n[9]*0.2563124 
       + 0.6*0.06664788
       + a_J[9]*0.0191103)

0.048398114613000004

In [74]:
alpha_1 = np.array([0.25, 0.15, 0.009, 0.0385, 0.0486, 0, 0, 0, 0.0001, 0.00035, 0])
alpha_1 / np.sum(alpha_1)

array([5.03473970e-01, 3.02084382e-01, 1.81250629e-02, 7.75349914e-02,
       9.78753398e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       2.01389588e-04, 7.04863559e-04, 0.00000000e+00])

In [86]:
alpha_2 = np.array([0.1510422, 0.0604229, 0.2963477, 
                                        0.0098184, 0.0075282, 0.0015104, 
                                        0.0004531, 0.01163025, 0.0112615, 
                                        0.0392749, 0])
alpha_2 / np.sum(alpha_2)

array([0.25631237, 0.10253516, 0.50288979, 0.01666142, 0.01277504,
       0.00256309, 0.00076889, 0.01973605, 0.0191103 , 0.06664788,
       0.        ])

# Model B

In [117]:
A_ref = np.zeros((9, 9))
A_ref[0,0] = .6
A_ref[0,1] = .4*.7
A_ref[0,2] = .4*(.1 + .1*.8)
A_ref[0,3] = .4*(.1 + .1*.2*.5)
A_ref[0,6] = .4*.1*.2*.5*.2
A_ref[0,7] = .4*.1*.2*.5*.7
A_ref[0,8] = .4*.1*.2*.5*.1
A_ref[np.arange(1,3),np.arange(2,4)] = [0.97, 0.5]
A_ref[np.arange(1,3),np.arange(4,6)] = [0.01, 0.05]
A_ref[1,3] = .01*.5
A_ref[1,6] = .2*(.01*.5+.01)
A_ref[1,7] = .7*(.01*.5+.01)
A_ref[1,8] = .1*(.01*.5+.01)
A_ref[2,6] = .2*(.4+.05)
A_ref[2,7] = .7*(.4+.05)
A_ref[2,8] = .1*(.4+.05)
A_ref[3,6] = .2
A_ref[3,7] = .7
A_ref[3,8] = .1
A_ref[np.arange(4,6),np.arange(2,4)] = [0.5, 0.9]
A_ref[np.arange(4,6),np.arange(4,6)] = [0.5, 0.1]
A_ref[6,6] = .9 + .1*.1*.2*.5*.2
A_ref[6,1] = .1*.7
A_ref[6,2] = .1*(.1+.1*.8)
A_ref[6,3] = .1*(.1+.1*.2*.5)
A_ref[6,7] = .1*.1*.2*.5*.7
A_ref[6,8] = .1*.1*.2*.5*.1
A_ref[7,7] = 0.6
A_ref[7,8] = 0.4
A_ref[8,8] = 1

In [138]:
P_0 = [0.5, 
       0.5*0.7,
       0.5*(0.1 + 0.1*0.8),
       0.5*(0.1 + 0.1*0.2*0.5),
       0, 
       0,
       0.5*0.1*0.2*0.5*0.2,
       0.5*0.1*0.2*0.5*0.7,
       0.5*0.1*0.2*0.5*0.1]

In [139]:
P_0

[0.5,
 0.35,
 0.09000000000000001,
 0.05500000000000001,
 0,
 0,
 0.0010000000000000002,
 0.0035000000000000005,
 0.0005000000000000001]

In [140]:
#alpha(.,1)
alpha1 = np.multiply(0.5, P_0)
alpha1[2] *= 2 * 0.1
alpha1[3] *= 2 * 0.7
alpha1[-1] = 0
alpha1, alpha1/np.sum(alpha1)

(array([0.25   , 0.175  , 0.009  , 0.0385 , 0.     , 0.     , 0.0005 ,
        0.00175, 0.     ]),
 array([0.52659294, 0.36861506, 0.01895735, 0.08109531, 0.        ,
        0.        , 0.00105319, 0.00368615, 0.        ]))

In [143]:
#alpha(., 2)
alpha2 = np.matmul(alpha1, A_ref)
alpha2 *= np.array([0.5, 0.5, 0.9, 0.3, 0.5, 0.5, 0.5, 0.5, 0])
alpha2

array([0.075     , 0.0350175 , 0.1689831 , 0.00491415, 0.000875  ,
       0.000225  , 0.00484255, 0.01668642, 0.        ])

In [144]:
#alpha(., 3)
alpha3 = np.matmul(alpha2, A_ref)
alpha3 *= np.array([0.5, 0.5, 0.1, 0.7, 0.5, 0.5, 0.5, 0.5, 0])
alpha3

array([0.0225    , 0.01066949, 0.00398916, 0.06175568, 0.00039384,
       0.00423583, 0.01035781, 0.03363126, 0.        ])

# Backward

In [3]:
beta3 = np.array([0.5, 0.5, 0.1, 0.7, 0.9, 0.5, 0.5, 0.5, 0.5, 0.5, 0])
beta3_scaled = beta3 / np.sum(beta3)
beta3_scaled, beta3

(array([0.09615385, 0.09615385, 0.01923077, 0.13461538, 0.17307692,
        0.09615385, 0.09615385, 0.09615385, 0.09615385, 0.09615385,
        0.        ]),
 array([0.5, 0.5, 0.1, 0.7, 0.9, 0.5, 0.5, 0.5, 0.5, 0.5, 0. ]))

In [4]:
A_t = np.array([[-5.1082557e-01, -7.3682724e+01, -7.3682724e+01, -7.3682724e+01,
   -7.3682724e+01, -7.3682724e+01, -7.3682724e+01, -7.3682724e+01,
   -7.3682724e+01, -7.3682724e+01, -7.3682724e+01],
  [-1.4271162e+00, -7.3682724e+01, -7.3682724e+01, -7.3682724e+01,
   -7.3682724e+01, -7.3682724e+01, -7.3682724e+01, -7.3682724e+01,
   -2.8134105e+00, -7.3682724e+01, -7.3682724e+01],
  [-2.6310890e+00, -3.0459363e-02, -7.3682724e+01, -7.3682724e+01,
   -7.3682724e+01, -6.9314718e-01, -7.3682724e+01, -7.3682724e+01,
   -4.0173836e+00, -7.3682724e+01, -7.3682724e+01],
  [-3.1235654e+00, -5.2983174e+00, -6.9314718e-01, -7.3682724e+01,
   -7.3682724e+01, -7.3682724e+01, -6.9314718e-01, -7.3682724e+01,
   -4.5098600e+00, -7.3682724e+01, -7.3682724e+01],
  [-3.1419146e+00, -5.5214610e+00, -1.1394343e+00, -5.1082569e-01,
   -7.3682724e+01, -7.3682724e+01, -7.3682724e+01, -6.9314718e-01,
   -4.5282087e+00, -7.3682724e+01, -7.3682724e+01],
  [-7.3682724e+01, -4.6051702e+00, -7.3682724e+01, -7.3682724e+01,
   -7.3682724e+01, -6.9314718e-01, -7.3682724e+01, -7.3682724e+01,
   -7.3682724e+01, -7.3682724e+01, -7.3682724e+01],
  [-7.3682724e+01, -7.3682724e+01, -2.9957323e+00, -7.3682724e+01,
   -7.3682724e+01, -7.3682724e+01, -6.9314718e-01, -7.3682724e+01,
   -7.3682724e+01, -7.3682724e+01, -7.3682724e+01],
  [-7.3682724e+01, -7.3682724e+01, -7.3682724e+01, -1.2039728e+00,
   -7.3682724e+01, -7.3682724e+01, -7.3682724e+01, -6.9314718e-01,
   -7.3682724e+01, -7.3682724e+01, -7.3682724e+01],
  [-8.7403374e+00, -6.1192980e+00, -3.6496589e+00, -3.9120231e+00,
   -1.6094379e+00, -7.3682724e+01, -7.3682724e+01, -7.3682724e+01,
   -1.0531610e-01, -7.3682724e+01, -7.3682724e+01],
  [-7.4875741e+00, -4.8665352e+00, -2.3968959e+00, -2.6592600e+00,
   -3.5667497e-01, -7.3682724e+01, -7.3682724e+01, -7.3682724e+01,
   -8.8738680e+00, -5.1082557e-01, -7.3682724e+01],
  [-9.4334841e+00, -6.8124452e+00, -4.3428059e+00, -4.6051702e+00,
   -2.3025851e+00, -7.3682724e+01, -7.3682724e+01, -7.3682724e+01,
   -1.0819778e+01, -9.1629070e-01,  0.0000000e+00]])
A_t = np.exp(A_t)
em2 = np.array([0.5, 0.5, 0.9, 0.3, 0.1, 0.5, 0.5, 0.5, 0.5, 0.5, 0])
beta2 = em2 * np.matmul(beta3, A_t)
beta2

array([0.24862003, 0.05702499, 0.64934999, 0.22049999, 0.045     ,
       0.15      , 0.3       , 0.35      , 0.249655  , 0.15000001,
       0.        ])

In [6]:
beta2 / (1-beta3)

array([0.49724005, 0.11404998, 0.72149999, 0.73499997, 0.44999999,
       0.3       , 0.6       , 0.7       , 0.49931   , 0.30000002,
       0.        ])